### ISSUE TITLE
Publish package

### ISSUE THREAD

**Issue by thewillyhuman** [weso/document#3]
The Document API has been fully tested, now it can be published somewhere. My preference would be to use github packages that allow to publish this kind of APIs. But bintray or other platforms are welcome too. What do you think @labra ?

**Comment by labra** [comment]
If you want to git a try to github pages, that's fine for me. What would be great is to automate the publication from Travis once the tests pass and maybe the version changes.

**Comment by thewilly** [comment]
> 
> 
> If you want to git a try to github pages, that's fine for me. What would be great is to automate the publication from Travis once the tests pass and maybe the version changes.

My aim was more focused on publish the package somewhere automatically, in order to be able to import it as a dependency from maven, gradle, sbt...

**Comment by labra** [comment]
It would be great to advance this issue and publish it as a github package. In fact, we could use this one as a test in order to publish the rest of shaclex-related packages to github packages.

Did you try to do it?

**Comment by thewillyhuman** [comment]
Will try it this week. I will post any update here.

**Comment by thewillyhuman** [comment]
@labra are you used tu publish the releases over cli or relaying on the continuos integration, when a release is published on GitHub?

**Comment by labra** [comment]
At this moment we are publishing it manually but I would prefer to integrate it with git workflows.

**Comment by thewillyhuman** [comment]
Perfect!

**Comment by thewillyhuman** [comment]
## Updates from 2021, feb 7.
In another a gradle repo that I use for tests I managed to publish the generated package on GitHub by means of the following configuration:

```gradle
plugins {
    id 'java'
    id("maven-publish")
}

repositories {
    mavenCentral()
}

dependencies {
    testCompile group: 'junit', name: 'junit', version: '4.12'
}

publishing {
    repositories {
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/thewillyhuman/gradle-java-template")
            credentials {
                username = project.findProperty("gpr.user") ?: System.getenv("GITHUB_ACTOR")
                password = project.findProperty("gpr.key") ?: System.getenv("GITHUB_TOKEN")
            }
        }
    }
    publications {
        gpr(MavenPublication) {
            from(components.java)
        }
    }
}
```

Now, I have to migrate this to `sbt`. There is a [plugin](https://github.com/djspiewak/sbt-github-packages), that should help. But, for now, still haven't been successful. At the [issues](https://github.com/djspiewak/sbt-github-packages/issues) section of the repository of the plugin we can find lots information about people who had the same problems. 
Then, we need to integrate it with GitHub Actions. Again, in my test repository I have managed to do so with the following workflow:

```YAML
name: Publish release

on:
  release:
    types: [published]

jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Publish artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        # The GITHUB_REF tag comes in the format 'refs/tags/xxx'.
        # If we split on '/' and take the 3rd value,
        # we can get the release name.
        run: |
          NEW_VERSION=$(echo "${GITHUB_REF}" | cut -d "/" -f3)
          echo "New version: ${NEW_VERSION}"
          echo "Github username: ${GITHUB_ACTOR}"
          cd library
          ../gradlew -Pversion=${NEW_VERSION} publish
```
The previous workflow, does not only publish a package in the GitHub Packages Registry. But also names it automatically as the GitHub Release version. This, I think, is very interesting. As it it a safeguard against duplicated releases due to un-updated sbt files.
